src/prompts.rs
This new feature won't change existing behaviours but will allow some users of this library to allow for empty password.
=> add function to allow empty password in `PasswordInput`

src/prompts.rs
cargo test was failing due to an issue in the documentation for Input.
=> Fix Input documentation

examples/select_opt.rs, src/prompts.rs, src/select.rs
Hi,
I want to use Select but allow the user to quit without selecting an Item. I have added interact_opt() and interact_on_opt() methods to Select. These methods return Result<Option<usize>> instead of Result<usize>.
=> Allow Select to quit without selecting an Item with Esc or q

src/select.rs
When using a crate like `textwrap` to wrap ridiculously long lines to use with a select prompt, the rendering mechanism would still clear a few lines too much.
Therefore: while counting the characters per line, take newlines into consideration and make it a separate line.
=> Fix long multi-line select rendering

src/select.rs
When pressing the right arrow key in a paged select the code goes to the previous page instead of the next one. In addition to being wrong, this also panics because of integer underflow when on the first page. This PR fixes this bug.
=> Fix right arrow behavior on paged select

src/theme.rs
This pull request fixes a missing whitespace after the text:
```rust
// Before, this did not add a whitespace after the text. Rendering as "text":
Confirmation::new().with_text("text").show_default(false).interact()
// While these, before rendered as "text [Y/n] ":
Confirmation::new().with_text("text").show_default(true).interact().unwrap();
Confirmation::new().with_text("text").interact().unwrap();
```
It also removes a whitespace before, if there is no text:
```rust
// After interaction, these would before render as e.g. " yes"
Confirmation::new().interact().unwrap();
Confirmation::new().show_default(false).interact().unwrap();
```
This also fixing The same issue is fixed for `Input`:
```rust
// Before, this would render as ` [default]: ` …
```
=> Fixed prompt formatting

examples/buffered.rs, src/prompts.rs, src/select.rs
Right now, buffered terminals (e.g. `Term::buffered_stderr()`, etc.) cannot be used with any of the interactive controls, as they never call `Term::flush`. Using a buffered terminal reduces the amount of flickering when scrolling through longer `Select` or `Checkboxes` lists. This PR adds the necessary flush calls and an example using a buffered stderr terminal.
=> Support for buffered terminals

src/prompts/password.rs
One case was not covered: in a case when confirmation is wrong the loop starts again and the initial password stays in memory. Zeroize it as well, and clone the final password out.
Solves #49.
`cargo test` is OK.
`cargo run --example password` is OK.
=> Zeroize password while looping

examples/continue.rs, src/prompts/input.rs
Closes #57 
This replaces the input prompt's use of:
``` rust
let input = if let Some(initial_text) = self.initial_text.as_ref() {
term.read_line_initial_text(initial_text)?
} else {
term.read_line()?
};
```
with a new block that uses `console::term::read_key()`
This allows us to avoid printing control characters.
=> add new fns similar to interact that ignore unprintable characters

src/prompts/select.rs
First time I used dialoguer I noticed that documentation is somewhat lacking, while the crate itself is quite nice.
I therefore thought to add some rustdocs in order to make it simpler for future user to use this library. This pull request contains enhancements in documentation for Select prompt. If it is welcome, I could create similar ones for other prompts.
I also believe that good documentation could make this crate more accesible, thus more popular.
=> Add rustdocs for select prompt

src/prompts/confirm.rs
`Confirm::with_text` was deprecated. The example should no longer use it.
=> Updated example for Confirm

src/prompts/multi_select.rs
Not 100% sure what the behaviour should be in this case,
We could set pages to 0 and show nothing to the user (which is confusing)
or we could return an empty Vec  immediately (which is also confusing but slightly less so I think)
=> Fix divide by zero when capacity is 0

examples/confirm.rs, src/prompts/confirm.rs
=> Add option to Confirm that forces user to enter 'y' or 'n' to continue

src/prompts/confirm.rs, src/prompts/input.rs, src/prompts/multi_select.rs, src/prompts/sort.rs
See https://github.com/jamesmcm/vopono/issues/19 for how this caused issues previously.
Also fixed current tests to run for current codebase.
Note #43 means that the validators now need to take `&String` not `&str` (since the type signature dictates `&T`). This is a bit painful.
This is because for the Input<T>, T is the owned type i.e. String, so then the closure (on `&T`) must accept &String and cannot accept &str. I tried to work around this with AsRef but it won't work unless we change the T to be the base type i.e. &str and then use ToOwned to make it return the owned type (we could even use Cow). But this is a lot of work and would change all instantiations of `Input<T>`.
=> Remove 'static restriction on Input<T> validate_with() and fix tests

examples/buffered.rs, examples/confirm.rs, examples/continue.rs, examples/edit.rs, examples/multi_select.rs, examples/password.rs, examples/select.rs, examples/select_opt.rs, examples/sort.rs, examples/validate_input.rs, examples/wizard.rs, src/prompts/input.rs, src/prompts/multi_select.rs, src/prompts/select.rs, src/prompts/sort.rs
Make examples use Rust 2018 syntax :slightly_smiling_face:
=> Fix clippy issues and remove extern crate statements from examples

Cargo.toml
This patch adds the command-line-interface category [0] to Cargo.toml
for better discoverability on crates.io and lib.rs.
[0] https://crates.io/categories/command-line-interface
=> Add command-line-interface category to Cargo.toml

src/edit.rs
It's an experiment pr to fix https://github.com/mitsuhiko/dialoguer/issues/87
=> fix args in vim -N -u NONE

CHANGELOG.md, Cargo.toml, examples/input.rs, src/prompts/input.rs, src/validate.rs
This allows mutable closures for validation, allowing stateful
validators.
This breaks BC. Input::interact*() now take &mut self instead of &self.
However, this shall not break most usres,
since (I think) users usually use Input in chained syntax
or call one of the &mut methods (like with_prompt) separately,
which would require a `let mut` anyway.
=> Allow FnMut for validate

src/prompts/select.rs
Noticed this small typo while going over the documentation.
=> Fix typo: ereased -> erased

examples/confirm.rs, src/prompts/confirm.rs, src/theme.rs
Adds `Confirm::interact_opt` and `Confirm::interact_on_opt` to handle situations where the user
wishes to answer neither "yes" nor "no".
Resolves #100 
***
=> Allow confirm with no choice

Cargo.toml, src/lib.rs
The `Editor` functionality currently depends on `tempfile` which is a pretty hefty dependency, so it would be nice if it were an optional feature since many uses of this library don't need the edit functionality.
With the current PR:
```bash
$ cargo tree --no-default-dependencies
dialoguer v0.8.0
├── console v0.14.1
│   ├── lazy_static v1.4.0
│   ├── libc v0.2.91
│   ├── regex v1.4.5
│   │   └── regex-syntax v0.6.23
│   ├── terminal_size v0.1.16
│   │   └── libc v0.2.91
│   └── unicode-width v0.1.8
├── lazy_static v1.4.0
└── zeroize v1.2.0
```
```bash
$ cargo tree # (with default features)
dialoguer v0.8.0
├── console v0.14.1
│   ├── lazy_static v1.4.0
│   ├── libc v0.2.91
│   ├── regex v1.4.5
│   │   └── regex-syntax v0.6.23
│   ├── terminal_size v0.1.16
│   │   └── libc v0.2.91
│   └── …
```
=> Make Editor and tempfile dependency optional

Cargo.toml, examples/history.rs, src/history.rs, src/lib.rs, src/prompts/input.rs, src/theme.rs
* Added support for optional history processing to `Input`.  
Up/Down arrow keys are read in `interact_text_on` and allow for history to be read via a user supplied function.
History is written after successful input validation via the same user supplied function.
=> Add support for optional history processing to `Input`

.github/workflows/ci.yml
The `zeroize` crate now uses `const` generics for the [Zeroize trait](https://docs.rs/zeroize/1.4.1/zeroize/trait.Zeroize.html#impl-Zeroize-4). Since this feature is only available in [Rust 1.51 and above](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#const-generics-mvp), the automated testing (which was previously set to Rust 1.40) will always fail to compile. Thus, this PR bumps up the minimum stable Rust version to 1.51, which should finally allow tests to compile.
=> Chore: bump minimum stable Rust version to 1.51

Cargo.toml, src/lib.rs, src/prompts/fuzzy_select.rs, src/prompts/input.rs, src/prompts/mod.rs, src/prompts/password.rs
This PR continues the work done on #120. However, instead of disabling `zeroize` (which implies insecure inputs), this approach disables the `password` module altogether. As discussed in #120, we must enforce that the user must have either a **secure** password input or no password input at all—"all or nothing", so to speak.
For backwards-compatibility, the `password` feature is enabled by default.
=> Refactor: treat `password` module as an optional feature

examples/paging.rs, examples/select.rs, src/lib.rs, src/paging.rs, src/prompts/multi_select.rs, src/prompts/select.rs, src/prompts/sort.rs, src/theme.rs
This addresses #125 
The following things have been addressed:
* I extracted all the functions regarding the paging functionality into an own module to reduce code redundancy
* The module detects if paging is needed and (de)activates paging accordingly
* The module is able to update terminal information via an `update()` function. This allows the rendering to adjust to terminal resizing. (But since the `match term.read_key()?` seems to block the rendering loop, the healing will only be achieved after the next key press)
* All prompts that are related to item lists (except `fuzzy-select` for now) are adjusted to use the new paging module.
* The prompt rendering functions have an additional parameter to be able to print the paging information
Currently the whole thing behaves like this when …
=> Fix paging

src/prompts/input.rs
```console
cargo doc
Documenting dialoguer v0.9.0 (/home/miraclx/projects/git/mitsuhiko/dialoguer)
warning: unresolved link to `default`
--> src/prompts/input.rs:98:46
|
98 |     /// The default behaviour is to append [`default`] to the prompt to tell the
|                                              ^^^^^^^ no item named `default` in scope
|
= note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
= help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
warning: `dialoguer` (lib doc) generated 1 warning
```
=> fix(doc): unlinked ref

src/prompts/multi_select.rs, src/prompts/select.rs, src/prompts/sort.rs
Follow up to #144
Ensure to properly clear the terminal when paging to a `max_length` less than `self.items`
=> fix: properly clear term when paging

src/prompts/confirm.rs, src/prompts/fuzzy_select.rs, src/prompts/input.rs, src/prompts/multi_select.rs, src/prompts/password.rs, src/prompts/select.rs, src/prompts/sort.rs
Sometimes, the whole prompt sneakily fizzing out is useful. Interact, sure.. but afterwards, clean everything up.
=> feat: support optionally disabling the report after interaction

examples/completion.rs
Resolves [Buffer overflow panic using completion example #168](https://github.com/mitsuhiko/dialoguer/issues/168).
=> Fix buffer overflow in completion example

src/prompts/fuzzy_select.rs, src/theme.rs
This implements #163.
In the `SimpleTheme`, the matched characters are printed bold, the default `ColorfulTheme` prints the characters in bold and yellow.
The highlighting is enabled by default and can be turned off via `.highlight_matches(false)` in the prompt builder.
Here's an example:
=> Feature: Add Fuzzy Select match highlighting

Cargo.toml
Docs.rs doesn't build optional features by default, and so e.g. `FuzzySelect` does not show up and cannot be searched for.
This change will tell it to build docs for every optional feature.
=> Tell docs.rs to document all features

src/theme.rs
This fixes #195.
I decided to go for the bold-only option (No3 in https://github.com/mitsuhiko/dialoguer/issues/195#issuecomment-1121610065).
=> Fix: [Fuzzy-Select] Apply active style to active item

src/prompts/fuzzy_select.rs
Hi!
In this PR, I've made a small but useful extension to `FuzzySelect` that enables the user to decide how many options will be displayed at one time, rather than the default of the terminal height minus 2.
Example code:
```rust
FuzzySelect::with_theme(&ColorfulTheme::default())
.with_prompt("What is your guess?")
.with_visible_term_rows(5_usize)
.items(word_slice)
.report(true)
.default(0)
.interact()?;
```
Here's an example of how it looks with `visible_term_rows = 5`:
I'm still somewhat new to Rust, let me know if there's any code style that can be improved.
=> Enable customization of number of rows for FuzzySelect

src/prompts/multi_select.rs
Closes #139.
Implement checking / unchecking all items in `MultiSelect` using the key <kbd>a</kbd>. Tested locally by running the `multi_select` example.
- The key <kbd>a</kbd> is used instead of the right arrow key, as seen in the screenshot of `gh` in the referred issue, because the right arrow key is already bound to page navigation.
- If all items are currently checked, uncheck all of them. Otherwise, all items are checked.
=> MultiSelect: Implement checking and unchecking all

src/lib.rs
I added a mention to the available features in the main documentation (since I needed to look in the Cargo.toml for them myself :sweat_smile: )  
In the second commit I added the `full` feature for convenience, because that seems to be a convention across popular crates. I'm happy to drop that commit and just keep the first one, if you prefer not to add that feature. :)
=> Adds the `full` feature convention for convenience

src/prompts/fuzzy_select.rs
Adds the ability to start a `FuzzySelect` from a non-empty string, by specifying an initial `search_term`.
```rust
let selections = &[
"A Pile of sweet, sweet mustard",
"Carrots",
"Peas",
"Pistacio",
"Mustard",
"Potato",
"Pizza",
];
let selection = FuzzySelect::with_theme(&ColorfulTheme::default())
.with_prompt("Pick your flavor")
.default(0)
.search_term("P") // specify initial search term
.items(&selections[..])
.interact()
.unwrap();
```
=> Added starting search term to `FuzzySelect`

src/prompts/input.rs
This is similar to https://github.com/mitsuhiko/dialoguer/pull/232
The issue only happens on buffered terminals
=> Flush terminal when initial text is used

Cargo.toml, src/edit.rs
This was reported by a user of my project at https://github.com/arxanas/git-branchless/issues/718. In their case, they are running Windows, and the path to their executable naturally includes the substring `Program Files`, which has spaces in it. These spaces are not handled properly by `dialoguer`.
An alternative would be to offer an option to disable splitting on space, which would then allow the caller to manually parse the executable string on their own, in the event that it contains spaces; or we could add an alternative method to `Editor` (and update the internal state) so that we can construct it with a string that might contain both the executable and arguments, which will then do the space-splitting behavior.
=> Fix: Handle executable with spaces in name

src/prompts/select.rs
In the docs for select (didn't have time to check the other functions) fixed the `use console::Term;` includes (which would cause an error).
Without explicitly installing `console` the docs would yield an error out of the box. Since you're re-exporting `console` it would make sense to take it from the main entry point.
=> Fixed docs for select

src/prompts/fuzzy_select.rs
When a buffered terminal is used (like `Term::buffered_stderr()`), the current char won't always be printed if the user is typing a string that doesn't match anything.
This PR fixes this.
Also, moving the flush to outside the loop seems to be more efficient.
=> Always display current char when terminal is buffered

src/prompts/input.rs
I found this issue when pressing the `Ctrl` key while using `Input`, which causes it to return `Err(Not a terminal)` under windows (but works fine on Linux). In this case, I was in the process of pressing `Ctrl + C` in order to terminate the program.
There are a few keystrokes which cause `console-rs` to produce `Unknown` keys when running under Windows. At the time of this commit this includes pressing the `Control` key, but also previously included `Shift` and `Alt`.
- https://github.com/console-rs/console/issues/83
- https://github.com/console-rs/console/issues/102
Pressing these keys under a *nix terminal does not appear to produce a "key" at all - rather the user must press a complete key chord before `Term::read_key()` will produce a result. 
Looking at the `console-rs` source, from …
=> Ignore Unknown keys

src/edit.rs, src/theme.rs
Hi there,
I had a look into what the cause of the issue is for #237.
It turns out in the calculation for `clear_preserve_prompt` we assume it would only be a single new line that could be added per item but a line could expand easily to 3 or more lines. So I added a calculation to add as many lines as needed here.
I hard coded the `prefix_width` as I believe it's not adjustable to be more than 2 but I wasn't sure and I only tested with `Select`. Tests seem to pass though. Happy to make this bit dynamic (which is why I called it out as an extra variable) but wanted to check here first.
Fixes #237
=> Fix long lines in select failing size calcuations

src/prompts/confirm.rs
=> Return Err on Confirm's read_key when not a terminal

src/theme.rs
This appears like an oversight: we clear the last `self.height+self.prompt_height` lines from the output; we set `height` to 0, but not `prompt_height`. We should also reset prompt_height.
This can cause issues if we were to call clear() twice in a row: we would clear prompt_height lines more than we should.
=> fix: also reset self.prompt_height in `TermThemeRenderer::clear`.

examples/password.rs, src/prompts/password.rs, src/validate.rs
Closes #150 
Implement validation function in `Password` which would be useful for checking the strength of passwords. This PR includes:
- Adding `validator` property and `validate_with` method to `Password`
- Refactoring the password confirmation process in order to reduce complexity
- Adding validation process in `interact_on` method
- Minor update on an example code
=> Add `validate_with` function to password prompt

src/prompts/fuzzy_select.rs
This pull request introduces a vim mode to `FuzzySelect`.
Vim mode works as follows:
1. The user can press Escape to enter vim mode
2. The user can use hjkl to navigate
3. The user can still select with Enter, or press i/a to enter more text
This is based on the vim mode from <https://github.com/go-survey/survey>.
To achieve this I've added the following changes:
- Keep track of `vim_mode`.
- Add support for hjkl keys, only when `vim_mode` is true.
- Add the `FuzzySelect::enable_vim_mode` method.
These changes have the following benefits:
- They allow vim users to use vim bindings, even in a fuzzy select.
- The behavior is opt-in, so other users won't even notice.
- The behavior is the same as many other tools, one example being Telescope for Neovim.
I hope my contribution can be of use!
=> Add vim mode to `FuzzySelect`

src/prompts/confirm.rs
On windows if you hit `Ctrl` or some other unmapped key the confirm prompt fails with an error otherwise.
=> Do not error on Key::Unknown in input and confirm

src/prompts/confirm.rs, src/prompts/input.rs, src/prompts/multi_select.rs, src/prompts/password.rs, src/prompts/select.rs, src/prompts/sort.rs
Fixes #229
Fixes #148
Follows #260
=> Make inputs fail if not connected to a terminal

src/prompts/input.rs
One of the main reasons to use `history` is the ability to correct mistakes.
When used with validation, history is appended after validation, so the input not passing it doesn't end up in history.
Therefore, the user needs to re-type the whole text.
With this PR, history is written before input validation, so we have a complete history. This behavior is in line with tools like `bash`.
```rust
Input::with_theme(&theme)
.with_prompt("E-mail")
.history_with(&mut history)
.validate_with(|email: &String| -> Result<(), String> {
if !email.contains('@') {
return Err(format!("{}: '{}'", "Invalid email address", email));
}
})
.interact_text()
.expect("Unable to read email")
```
=> Record input to history before validation

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml
Found your CI failing.
The easiest is to bump MSRV since 5 months passed after the previous update.
This fixes failing CI on 44cb900
=> Update MSRV to 1.59 -> 1.63

examples/history.rs, examples/history_custom.rs, src/history.rs, src/lib.rs, src/prompts/input.rs
As it stands, if one wants to have an input with history, one has to define a custom struct and implement the History trait for it, which is quite some boilerplate code (See [examples/history.rs](https://github.com/mitsuhiko/dialoguer/blob/master/examples/history.rs)). Since in most simple applications, one probably doesn't need any custom history logic (limited size / no duplicates / etc.), simply providing a default implementation for `Vec` and `VecDeque` seems sensible to me.
The `VecDeque` implementation is very straightforward and equivalent to the provided example, except without limiting the size. For the `Vec` implementation we have to index from the back, which requires checking in advance that the `pos` is in bounds, since otherwise we end up subtracting a `usize` below zero, …
=> Provide a basic default implementation of `History`

examples/password.rs, src/prompts/password.rs
A `password` example contains a typical Rust bug when String's number of bytes is checked instead of characters.
`Password::interact_on()` doc is updated here too.
=> Count characters in `password` example instead of bytes

CHANGELOG.md, src/theme/colorful.rs
Resolves https://github.com/console-rs/dialoguer/issues/172
=> Remove `ColorfulTheme.inline_selections`

CHANGELOG.md, src/prompts/fuzzy_select.rs, src/theme/colorful.rs, src/theme/mod.rs
Fixes #181.
Use the [`str::char_indices()`](https://doc.rust-lang.org/std/primitive.str.html#method.char_indices) to keep valid byte offsets in memory.
Also add handling of  the `Delete` key.
=> Fix panic in fuzzy-select when using non-ASCII characters

src/prompts/input.rs
Extracted from #278 as requested.
The "term.features().is_attended()" check can never be reached because "term.is_term()" is checked at the beginning of the method (iiuc the checks are strictly equivalent).
Additionnally, the 'unwrap' call in the dead code forced a 'Debug' trait bound on the <T as FromStr>::Err associated type.
Therefore i removed both the dead code and the now unnecessary trait bound.
=> Remove dead code and  'Debug' trait bound on Input's 'interact_text*' methods

src/paging.rs, src/prompts/select.rs
Hello,
I extracted the recomputation of the page into a separate method to fix the default selection not being on the first page without hiding the prompt.
=> fix #281 : Select : prompt is no longer displayed

examples/select.rs
The prompt for the third dialogue in `examples/select.rs` says "Optionally pick your flavor", but the choice is not optional.  This PR removes the word "Optionally."
=> Fix prompt in `select.rs` example

Cargo.toml, src/error.rs, src/lib.rs
this nightly feature is plenty stable and shows some decent benefits for this crate
before and after:
<table>
<tr>
<td>
</td>
<td>
</td>
</table>
=> Document crate feature guarded items on docs.rs

src/error.rs
Implements `From` for `Error` for `std::io::Error` to allow the error type to be converted to a `std::io::Error` which makes it easier for those coming from the v0.10 version where it was using std::io::Error instead of a custom error type.
This makes it easier to deal with the error type for those in a console app who are already likely using `std::io::Result` as their return type (So they can use the try operator without having to map the error type).
Since the `std::io::Error` is flexible and can take any kind of error type as its cause. I've left a comment incase you decide to expand the error type to have more errors other than just `std::io::Error`
- Allow conversion from `Error` to `std::io::Error`
=> Add conversion between error types

src/prompts/fuzzy_select.rs, src/prompts/multi_select.rs, src/prompts/select.rs, src/prompts/sort.rs
Replaces the handling for adding multiple items to the `Select`, `FuzzySelect`, `MultiSelect`, and `Sort` they currently take a slice containing any number of values that can be converted into `String` through `ToString`, this change replaces taking a slice with instead taking anything that implement `IntoIterator` where the item is `ToString`.
This allows the items function to take any collection of values rather than only allowing slices, thus making something like the following possible: 
```rust
struct MyItem {
name: String,
// .. other struct items
}
let collection: Vec<MyItem> = vec![  /* Some list of items */ ];
let item_names = collection
.iter()
.map(|item| item.name.as_str());
Select::new()
.items(item_names);
```
- Make `items`, `items_checked` (and similar functions) accept an …
=> Accept items by iterator instead of slice

Cargo.toml, src/error.rs
Supercedes #318 as there's no need to update `thiserror` if it's no longer used :grin:
It was easy enough to match the functionality provided by `thiserror` with a manual implementation instead
=> refactor: replace `thiserror` with a manual impl
